**jax_various_tests.ipynb**

Arz

2024 MAY 19 (SUN)

In [1]:
import jax
import jax.numpy as jnp

### key split

key = jax.random.key(0)

In [2]:
_, *subkeys = jax.random.split(jax.random.key(0), 3)
print(subkeys)

2024-06-09 02:50:23.402886: W external/xla/xla/service/gpu/nvptx_compiler.cc:760] The NVIDIA driver's CUDA version is 12.2 which is older than the ptxas CUDA version (12.4.131). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.


[Array((), dtype=key<fry>) overlaying:
[3186719485 3840466878], Array((), dtype=key<fry>) overlaying:
[2562233961 1946702221]]


In [3]:
print(subkeys[0])

Array((), dtype=key<fry>) overlaying:
[3186719485 3840466878]


In [4]:
for subkey in subkeys:
    print(subkey)

Array((), dtype=key<fry>) overlaying:
[3186719485 3840466878]
Array((), dtype=key<fry>) overlaying:
[2562233961 1946702221]


### jnp array indexing

In [5]:
q_table = jnp.zeros((3, 2), dtype=jnp.float32)

print(q_table)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
state = 1
action = 0

print(q_table.at[state, action].set(7))
print(q_table)

[[0. 0.]
 [7. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
q_table = q_table.at[state, action].set(7)
x = q_table[state, action]
print(x, type(x))
x = q_table.at[state, action].get()
print(x, type(x))

7.0 <class 'jaxlib.xla_extension.ArrayImpl'>
7.0 <class 'jaxlib.xla_extension.ArrayImpl'>


# dimension

In [9]:
x = jnp.zeros((3, 2), dtype=jnp.float32)
print(x.shape)

jnp.expand_dims(x, 0)
print(x.shape)

x = jnp.expand_dims(x, 0)
print(x.shape)

(3, 2)
(3, 2)
(1, 3, 2)
